# Generated by Django 5.2.4 on 2025-07-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiaFlex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='Departamento',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
