# Generated by Django 5.2.4 on 2025-07-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiaFlex', '0002_linha_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pecas/'),
        ),
    ]
